name: fischtracker
description: A new Flutter project.

publish_to: 'none'
version: 0.0.3+13

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cloud_firestore: ^5.1.0
  cupertino_icons: ^1.0.8
  equatable: ^2.0.5
  firebase_auth: ^5.1.2
  firebase_core: ^3.2.0
  firebase_crashlytics: ^4.0.3
  firebase_ui_auth: ^1.15.0
  firebase_ui_firestore: ^1.6.4
  firebase_ui_oauth_apple: ^1.2.21
  firebase_ui_oauth_google: ^1.3.3
  flex_color_scheme: ^8.2.0
  flutter_riverpod: ^2.5.1
  flutter_svg: ^2.0.10+1
  go_router: ^14.2.1
  google_fonts: ^6.2.1
  google_sign_in: ^6.2.1
  intl: ^0.20.2
  logging: ^1.2.0
  riverpod_annotation: ^2.3.5
  rxdart: ^0.27.7
  shared_preferences: ^2.2.3

dev_dependencies:
  integration_test:
    sdk: flutter
  flutter_test:
    sdk: flutter
  flutter_driver:
    sdk: flutter
  build_runner: ^2.4.11
  custom_lint: ^0.6.4
  flutter_lints: ^4.0.0
  mocktail: ^1.0.4
  random_string: ^2.3.1
  riverpod_generator: ^2.4.0
  riverpod_lint: ^2.3.10

flutter:
  uses-material-design: true
  assets:
    - assets/fisch-tracker.svg

  fonts:
    - family: SocialIcons
      fonts:
        - asset: packages/firebase_ui_auth/fonts/SocialIcons.ttf
