name: fischtracker
description: A new Flutter project.

publish_to: 'none'
version: 0.0.3+13

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cloud_firestore: ^5.6.12
  cupertino_icons: ^1.0.8
  equatable: ^2.0.7
  firebase_auth: ^5.7.0
  firebase_core: ^3.15.2
  firebase_crashlytics: ^4.3.10
  firebase_ui_auth: ^1.17.0
  firebase_ui_firestore: ^1.7.2
  firebase_ui_oauth_apple: ^1.3.2
  firebase_ui_oauth_google: ^1.4.2
  flex_color_scheme: ^8.2.0
  flutter_riverpod: ^2.6.1
  flutter_svg: ^2.2.0
  go_router: ^14.8.1
  google_fonts: ^6.2.1
  google_sign_in: ^6.3.0
  intl: ^0.20.2
  logging: ^1.3.0
  riverpod_annotation: ^2.6.1
  rxdart: ^0.28.0
  shared_preferences: ^2.5.3

dev_dependencies:
  integration_test:
    sdk: flutter
  flutter_test:
    sdk: flutter
  flutter_driver:
    sdk: flutter
  build_runner: ^2.5.4
  custom_lint: ^0.7.6
  flutter_lints: ^6.0.0
  mocktail: ^1.0.4
  random_string: ^2.3.1
  riverpod_generator: ^2.6.5
  riverpod_lint: ^2.6.5

flutter:
  uses-material-design: true
  assets:
    - assets/fisch-tracker.svg

  fonts:
    - family: SocialIcons
      fonts:
        - asset: packages/firebase_ui_auth/fonts/SocialIcons.ttf
