name: fischtracker
description: A new Flutter project.

publish_to: 'none'
version: 0.0.2+11

environment:
  sdk: ">=2.19.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cloud_firestore: ^4.8.4
  cupertino_icons: ^1.0.5
  equatable: ^2.0.5
  firebase_auth: ^4.7.2
  firebase_core: ^2.15.0
  firebase_crashlytics: ^3.3.4
  firebase_ui_auth: ^1.6.2
  firebase_ui_firestore: ^1.5.6
  firebase_ui_oauth_apple: ^1.2.7
  firebase_ui_oauth_google: ^1.2.7
  flex_color_scheme: ^7.2.0
  flutter_riverpod: ^2.3.6
  flutter_svg: ^2.0.7
  go_router: ^10.0.0
  google_fonts: ^5.1.0
  google_sign_in: ^6.1.4
  intl: ^0.18.0
  logging: ^1.2.0
  riverpod_annotation: ^2.1.1
  rxdart: ^0.27.7
  shared_preferences: ^2.2.0

dev_dependencies:
  integration_test:
    sdk: flutter
  flutter_test:
    sdk: flutter
  flutter_driver:
    sdk: flutter
  build_runner: ^2.4.6
  custom_lint: 0.4.0
  flutter_lints: ^2.0.2
  mocktail: ^1.0.0
  random_string: ^2.3.1
  riverpod_generator: 2.2.4
  riverpod_lint: 1.4.0

flutter:
  uses-material-design: true
  assets:
    - assets/fisch-tracker.svg

  fonts:
    - family: SocialIcons
      fonts:
        - asset: packages/firebase_ui_auth/fonts/SocialIcons.ttf