name: fischtracker
description: A new Flutter project.

publish_to: 'none'
version: 0.0.2+10

environment:
  sdk: ">=2.19.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cloud_firestore: ^4.7.0
  cupertino_icons: ^1.0.5
  equatable: ^2.0.5
  firebase_auth: ^4.6.0
  firebase_core: ^2.12.0
  firebase_crashlytics: ^3.3.0
  firebase_ui_auth: ^1.4.0
  firebase_ui_firestore: ^1.5.0
  firebase_ui_oauth_apple: ^1.2.0
  firebase_ui_oauth_google: ^1.2.0
  flex_color_scheme: ^7.1.0
  flutter_riverpod: ^2.3.6
  flutter_svg: ^1.1.6
  go_router: 7.0.1
  google_fonts: ^4.0.4
  google_sign_in: ^6.1.0
  intl: ^0.18.0
  logging: ^1.1.1
  riverpod_annotation: 2.1.1
  rxdart: ^0.27.7
  shared_preferences: ^2.1.1

dev_dependencies:
  integration_test:
    sdk: flutter
  flutter_test:
    sdk: flutter
  flutter_driver:
    sdk: flutter
  build_runner: 2.4.2
  custom_lint: 0.4.0
  flutter_lints: ^2.0.1
  mocktail: ^0.3.0
  random_string: ^2.3.1
  riverpod_generator: 2.2.3
  riverpod_lint: 1.3.2

flutter:
  uses-material-design: true
  assets:
    - assets/fisch-tracker.svg

  fonts:
    - family: SocialIcons
      fonts:
        - asset: packages/firebase_ui_auth/fonts/SocialIcons.ttf