name: fischtracker
description: A new Flutter project.

publish_to: 'none'
version: 0.0.2+11

environment:
  sdk: ">=2.19.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cloud_firestore: ^4.9.2
  cupertino_icons: ^1.0.6
  equatable: ^2.0.5
  firebase_auth: ^4.10.0
  firebase_core: ^2.16.0
  firebase_crashlytics: ^3.3.6
  firebase_ui_auth: ^1.8.0
  firebase_ui_firestore: ^1.5.11
  firebase_ui_oauth_apple: ^1.2.11
  firebase_ui_oauth_google: ^1.2.11
  flex_color_scheme: ^7.3.1
  flutter_riverpod: ^2.4.1
  flutter_svg: ^2.0.7
  go_router: ^11.1.2
  google_fonts: ^6.1.0
  google_sign_in: ^6.1.5
  intl: ^0.18.0
  logging: ^1.2.0
  riverpod_annotation: ^2.1.6
  rxdart: ^0.27.7
  shared_preferences: ^2.2.1

dev_dependencies:
  integration_test:
    sdk: flutter
  flutter_test:
    sdk: flutter
  flutter_driver:
    sdk: flutter
  build_runner: ^2.4.6
  custom_lint: 0.5.3
  flutter_lints: ^2.0.3
  mocktail: ^1.0.0
  random_string: ^2.3.1
  riverpod_generator: 2.3.3
  riverpod_lint: 2.1.1

flutter:
  uses-material-design: true
  assets:
    - assets/fisch-tracker.svg

  fonts:
    - family: SocialIcons
      fonts:
        - asset: packages/firebase_ui_auth/fonts/SocialIcons.ttf
