# The Deliverfile allows you to store various App Store Connect metadata
# For more information, check out the docs
# https://docs.fastlane.tools/actions/deliver/

app_identifier("org.rozendallabs.fischtracker")
submit_for_review(false)
verify_only(true)
overwrite_screenshots(true)
# change this to upload new screenshots
skip_screenshots(true)
