# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  desc "Build release version and store it in build/app/outputs"
  lane :build_aab do
    Dir.chdir "../.." do sh("flutter", "build", "appbundle", "--release") end # Call Flutter Build
    gradle(task: 'bundle', build_type: 'Release')
  end

  desc "Distribute previously built to firebase, upload crashlytics symbols at the same time"
  lane :distribute_to_firebase do
    firebase_app_distribution(
      firebase_cli_token: ENV['FIREBASE_TOKEN'],
      app: "1:468951951198:android:bfa9eefc6b1e9e3c2411cf",
      android_artifact_type: "AAB",
      android_artifact_path: "../build/app/outputs/bundle/release/app-release.aab",
      groups: "OnlyMe",
      release_notes: "Automatic demo release",
    )
  end

  lane :distribute_to_playstore do
    upload_to_play_store(
      track: 'internal',
      release_status: 'draft',
      version_code: flutter_version()["version_code"],
      aab: "../build/app/outputs/bundle/release/app-release.aab",
      skip_upload_metadata: true,
      skip_upload_images: true,
      skip_upload_screenshots: true
    )
  end

  desc "Build and distribute all"
  lane :build_and_distribute do
    build_aab
    #distribute_to_firebase
    distribute_to_playstore
  end
end
